# Generated by Django 3.2.9 on 2021-11-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='foto1',
            field=models.ImageField(upload_to='uploads/% Y/% m/% d/'),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='foto2',
            field=models.ImageField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='foto3',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
