# Generated by Django 3.2.9 on 2021-11-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitehouse', '0003_auto_20211115_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='foto1',
            field=models.ImageField(upload_to='whitehouse'),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='foto2',
            field=models.ImageField(upload_to='whitehouse'),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='foto3',
            field=models.ImageField(upload_to='whitehouse'),
        ),
    ]
