# Generated by Django 3.2.9 on 2021-12-17 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whitehouse', '0006_auto_20211124_0703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vivienda',
            options={'verbose_name': 'Vivienda', 'verbose_name_plural': 'Viviendas'},
        ),
        migrations.AddField(
            model_name='vivienda',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='vivienda',
            name='categoria',
        ),
        migrations.AddField(
            model_name='vivienda',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='whitehouse.categorias'),
            preserve_default=False,
        ),
    ]
