# Generated by Django 3.2.9 on 2021-12-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitehouse', '0007_auto_20211217_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vivienda',
            name='categoria',
        ),
        migrations.AddField(
            model_name='vivienda',
            name='categoria',
            field=models.ManyToManyField(to='whitehouse.Categorias'),
        ),
    ]
