# Generated by Django 3.2.9 on 2021-12-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitehouse', '0008_auto_20211220_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivienda',
            name='city',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vivienda',
            name='country',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vivienda',
            name='neiborhood',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
