# Generated by Django 3.2.9 on 2021-12-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitehouse', '0009_auto_20211221_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivienda',
            name='beds',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vivienda',
            name='capacity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vivienda',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
