# Generated by Django 3.2.9 on 2021-12-26 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('whitehouse', '0010_auto_20211222_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservas',
            name='vivienda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='whitehouse.vivienda'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservas',
            name='fecha_entrada',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='fecha_salida',
            field=models.DateTimeField(),
        ),
    ]
