# Generated by Django 3.2.9 on 2021-12-26 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whitehouse', '0011_auto_20211226_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservas',
            options={'verbose_name': 'reserva', 'verbose_name_plural': 'reservas'},
        ),
    ]
