# Generated by Django 3.2.9 on 2022-01-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitehouse', '0012_alter_reservas_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservas',
            options={'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterField(
            model_name='reservas',
            name='numero',
            field=models.IntegerField(blank=True),
        ),
    ]
