# Generated by Django 3.2.9 on 2022-01-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitehouse', '0014_reservas_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservas',
            options={'ordering': ['fecha_salida'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterField(
            model_name='reservas',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='m', help_text='Vivienda availability', max_length=1),
        ),
    ]
