# Generated by Django 3.2.9 on 2022-01-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitehouse', '0016_auto_20220110_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='fecha_entrada',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='fecha_salida',
            field=models.DateTimeField(),
        ),
    ]
