# Generated by Django 3.2.9 on 2022-01-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whitehouse', '0018_auto_20220110_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservas',
            options={'ordering': ['vivienda', 'fecha_salida'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
    ]
